### ISSUE TITLE
Cannot find module cookie when deploying on vercel

### ISSUE THREAD

**Issue by MaciejWiatr** [bjoluc/next-redux-cookie-wrapper#12]
![image](https://user-images.githubusercontent.com/44440856/102825123-759dab00-43de-11eb-9973-97e944db83f2.png)

The code im having issue with is: https://github.com/MaciejWiatr/Nextagram/tree/develop

**Comment by MaciejWiatr** [comment]
For now i've managed to overcome this issue by explicitly importing cookies module into my _app.js like that:
![image](https://user-images.githubusercontent.com/44440856/102835262-878b4800-43f6-11eb-9dd2-56405c450814.png)
however idk if it's really the best solution, not the cleanest one, that's for sure.

So I'd still like some suggestions, maybe i was doing something wrong

**Comment by MaciejWiatr** [comment]
However, I now see that this disables automatic static optimization and make the whole bundle a lot bigger D:

**Comment by bjoluc** [comment]
Thanks for reporting this and sorry for ghosting! I don't know what's going on with vercel there; do they build a server-side bundle? I certainly introduced this problem in d9e0315 as a reaction to #8, not meaning to affect server-side behavior.

> However, I now see that this disables automatic static optimization and make the whole bundle a lot bigger D:

Two different things here:
* Automatic static optimization is always disabled when `next-redux-cookie-wrapper` is in place, since it still uses the old v5 of `next-redux-wrapper`. #9 is related to that. Hope to build something neat in the next semester break.
* Bundle size: That's why I tricked Next.js into excluding the server-only `cookies` library from the bundle using the "eval cheat". It now seems that vercel walks into the same trap. I will need to look for a better solution here, didn't work with vercel yet...

**Comment by bjoluc** [comment]
I discovered the `browser` field in `package.json` to exclude the `cookies` library from the client build (and only the client build, hopefully :smile:). @MaciejWiatr Please try again and feel free to re-open the issue if the new version does not fix the problem!
