### ISSUE TITLE
Properties removed if not included in subtrees.

### ISSUE THREAD

**Issue by LucasLundJensen** [bjoluc/next-redux-cookie-wrapper#19]
Hi,

I've run into the scenario that I want to save part of my state in the cookies, but don't care about the rest.
My state "cart" contains `PRODUCTS`, `ITEMS` and `TOTAL` and I only want to "persist" `ITEMS`.

My issue now is that the `PRODUCTS` and `TOTAL` properties get removed competely on HYDRATE, as shown in the image here:
![Image of State](https://i.imgur.com/O3Fzcy8.png)

This is my code:

```TypeScript
const rootReducer = (state, action) => {
	switch (action.type) {
		case HYDRATE:
			return {
				...state,
				...action.payload
			}
		default:
			return combinedReducers(state, action);
	}
};

const makeStore = wrapMakeStore(() =>
	createStore(
		rootReducer,
		composeWithDevTools(
			applyMiddleware(
				nextReduxCookieMiddleware({
					subtrees: ["cart.ITEMS"],
					maxAge: 1209600000
				}),
				thunkMiddleware
			)
		)
	)
);
```

Is this just me not implementing proper state reconciliation? If it is, could you provide an example?

**Comment by bjoluc** [comment]
Hi @LucasLundJensen,
> Is this just me not implementing proper state reconciliation?

that seems to be the case. Internally, [only those state paths are ever modified](https://github.com/bjoluc/next-redux-cookie-wrapper/blob/dd0f4c653cd6d61da0fa7aa6c7d8e81c0c431618/main/src/state-walker.ts#L39-L41) that have been mentioned in the config. Also, a very similar scenario works in [the demo](https://github.com/bjoluc/next-redux-cookie-wrapper/blob/dd0f4c653cd6d61da0fa7aa6c7d8e81c0c431618/demo/store.ts) where the `page.title` and `page.subtitle` properties remain unchanged and only `page.counter` is touched.

The problem here seems to be with your root reducer that does not recursively reconcile state on the `HYDRATE` action. You may consider handling the `HYDRATE` action in each of your individual reducers instead (see the demo for an [example](https://github.com/bjoluc/next-redux-cookie-wrapper/blob/dd0f4c653cd6d61da0fa7aa6c7d8e81c0c431618/demo/store.ts#L30-L33)). Hope that helps!
