### ISSUE TITLE
Error:  Unexpected token "=", on Safari (=< 13.1)

### ISSUE THREAD

**Issue by QuentinCharlie** [bjoluc/next-redux-cookie-wrapper#45]
Hello there,

Using your ^2.2.0 version, i got the error screenshoted below on older safari (from 14.1 it works fine). I don't have the error with your 2.1.2 version tho.

<img width="957" alt="image" src="https://user-images.githubusercontent.com/55737901/203091151-359de3ec-75be-4799-8f03-1174a3a868ef.png">

I guess it's related to this https://stackoverflow.com/questions/60026651/safari-unexpected-token-expected-an-opening-before-a-methods-paramet

**Comment by bjoluc** [comment]
Hi @QuentinCharlie,

thanks for flagging this! It might have been my mistake when migrating from `tsdx` to `tsup`: I set the [`target` option](https://github.com/bjoluc/next-redux-cookie-wrapper/blob/22eb141b5904236b1b15b0a788e58afabb015104/main/package.json#L83) to `node12`, thinking that Next.js would transpile everything anyway. Now I'm not sure about that anymore, let me check...

**Comment by bjoluc** [comment]
I wasn't wrong, [it does](https://nextjs.org/docs/basic-features/supported-browsers-features) :tada:  So this is not a config thing in next-redux-cookie-wrapper, luckily. Next.js targets Safari 12+ by default. Which version did you try?

**Comment by QuentinCharlie** [comment]
Thanks for the quick response.
You meant the Next.js version we use ? It's the 12.3.0.

**Comment by bjoluc** [comment]
Sorry for not being clear, I meant the Safari version, given that Savari >= 12 should be supported (at least in latest Next.js). Did you try explicitly setting a browserslist config like [`defaults, Safari >= 11`](https://browsersl.ist/#q=defaults%2C+Safari+%3E%3D+11) in your `package.json`?

Closing this issue since transpiling production code for outdated browsers is up to Next.js/Babel :slightly_smiling_face:

**Comment by bjoluc** [comment]
Well, that's annoying. Out of curiosity, if you put
```js
class Foo {
  bar = 0;
}
new Foo();
```
into one of your project's files, you would get the same error, right? Does manually adding `@babel/plugin-proposal-class-properties` in a [custom babel config](https://nextjs.org/docs/advanced-features/customizing-babel-config) change anything?

**Comment by QuentinCharlie** [comment]
Adding the Foo code doesn't trigger any error and seems to works fine. (I can display the bar value on the app).

I tried to add a custom babel config to see if it solved the main issue, but sadly doesn't.

**Comment by bjoluc** [comment]
Any chance you can find out what causes the syntax error in `next-redux-cookie-wrapper`?

**Comment by QuentinCharlie** [comment]
The error in console, and where it is pointing at :
<img width="482" alt="image" src="https://user-images.githubusercontent.com/55737901/204490179-fb846b66-9127-48b0-a811-0686ddc25557.png">
<img width="225" alt="image" src="https://user-images.githubusercontent.com/55737901/204490318-91c26764-fab1-4bed-aead-e1e0254497c0.png">

I also cloned the repo and tested the demo, to see if somehow my application could be a vector of the issue, but i have the same issue (working fine except for those same older safari versions).

**Comment by bjoluc** [comment]
Does it make any difference when you change [the target in `main/package.json`](https://github.com/bjoluc/next-redux-cookie-wrapper/blob/22eb141b5904236b1b15b0a788e58afabb015104/main/package.json#L83)  to
```json
    "target": [
      "node12",
      "safari11"
    ],
```
and run `npm run build -w main`?

**Comment by QuentinCharlie** [comment]
Seems to works !

Also did just to be sure : 
- Started from a fresh clone
- Changed the tsup's target value with your snippet
- `npm install` then `cd demo && npm start`

Works like a charm :clap:

**Comment by bjoluc** [comment]
Next.js v12.3.0 (just like latest v13) [uses `@swc/core@1.2.203`](https://github.com/vercel/next.js/blob/ba4c575334796db92c93957afa97ef483cea3f2e/package.json#L72). The next step should be to check what causes the syntax error and if it was fixed in `@swc/core` by now – I couldn't find any existing [SWC issues](https://github.com/swc-project/swc/issues) on it. I can't research this myself, unfortunately, since I don't have access to Safari and don't know which exact syntax causes it. If you have some time available, please feel free to file an upstream issue.

Anyway, since fixing things upstream may take some time, LMK if you'd like me to publish a patch release of `next-redux-cookie-wrapper` for the time being.
