### ISSUE TITLE
Any way to retrieve cookie on server side?

### ISSUE THREAD

**Issue by thihathit** [bjoluc/next-redux-cookie-wrapper#5]
First of all, this is a great wrapper. Many thanks for putting effort.
Any way to retrieve cookie on server side except req.headers.cookie ?
I'm using nextJS's new getServerSideProps function.

**Comment by bjoluc** [comment]
Unfortunately not. I could of course add a utility function to do so, but I don't think that makes any sense. Let me explain why:
`next-redux-cookie-wrapper` uses version 5 of `next-redux-wrapper` under the hood, which is driven by defining a `getInitialProps()` method for the App component. This means, every landing request will be server-rendered. In other words, there's no benefit of using `getServerSideProps` and `getStaticProps` instead of `getInitialProps()`.
The future solution of `next-redux-wrapper` will use a different API and likely require each Page component, and each `getServerSideProps` or `getStaticProps` method to be wrapped. In addition to that, it will require writing a custom reducer (here's a discussion on that: https://github.com/kirill-konshin/next-redux-wrapper/pull/194).
I like the set-and-forget mentality of next-redux-cookie-wrapper and I don't think there's a similarly easy-to-use approach like the current one that still keeps the benefits of

**Comment by bjoluc** [comment]
So as an answer to your question: Considering the current implementation, you're best off using `getInitialProps` to get (and possibly modify) the Redux state. Let me know if you have any questions regarding that!

**Comment by thihathit** [comment]
Thank you for the nice explanation, I'm new to next.js and this helps me a lot that I should use `getInitialProps` for now. I'll be closing for now since the problem solved for me.

**Comment by gfortaine** [comment]
It looks like that you could have a look at what [next-iron-session](https://github.com/vvo/next-iron-session)  cc @vvo
